### ISSUE TITLE
Create Schematic Crash

### ISSUE THREAD

**Issue by ardissaps** [AlexIIL/LibMultiPart#52]
https://aofpaste.com/ebesuhasiy.yaml

**Comment by AlexIIL** [comment]
Ah, I was wondering when someone would run into this :p

For context, this is actually caused by LMP not supporting some of the vanilla schematic methods (block mirroring and rotation), so this bug could happen without create.

Currently vanilla only asks the block to rotate/mirror itself, and not the block entity - which is a problem for LMP since only the block entity stores part data, which is what actually needs to be rotated. What I can do though is store the requested rotation and mirroring in the block state, and then just actually rotate / mirror when it gets loaded.

**Comment by ardissaps** [comment]
I see, so it possible to fix it on 1.18.2 right? :p thank you for your time
